# Generated by Django 5.2.5 on 2025-08-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0002_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("credit_card", "Credit Card"),
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
